# Supabase Pooler Credentials
spring.datasource.url=jdbc:postgresql://YOUR_POOLER_HOST:6543/postgres
spring.datasource.username=YOUR_POOLER_USERNAME
spring.datasource.password=YOUR_SUPABASE_PASSWORD

# Mail Credentials
spring.mail.username=YOUR_GMAIL_ADDRESS@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD