spring.application.name=wellness



# 1. Host ต้องเป็นแบบ Pooler (พอร์ต 6543)
# สำคัญ: Host จะต้องมีคำว่า 'pooler' อยู่ในชื่อ เช่น aws-0-ap-southeast-1.pooler.supabase.com
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0

# 2. Username ของ Pooler มักจะมีจุด (.) คั่น
# เช่น postgres.bsqjznvmpwnwjwbzocia
spring.datasource.username=postgres.bsqjznvmpwnwjwbzocia
# 3. Password คือรหัสที่คุณเพิ่ง Reset หรือตั้งไว้
spring.datasource.password=Pimmda080348-

# 4. ตั้งค่า JPA ปกติ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 5. เพิ่มบรรทัดนี้เพื่อความชัวร์สำหรับการต่อผ่าน Pooler
spring.datasource.hikari.connection-timeout=30000
