spring.application.name=wellness

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Connection Settings
spring.datasource.hikari.connection-timeout=30000

# Mail Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ดึงรหัสผ่านลับจากไฟล์ที่คุณเพิ่งเปลี่ยนชื่อมาใช้
spring.config.import=optional:classpath:application-secret.properties